name: Update Action Tags
on: [workflow_call]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update Action Tags
        uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # latest
