name: Lint GitHub Action Workflows
on:
  pull_request:
    types: [synchronize, edited, opened]
  push:
    branches: [main]
  workflow_call:
jobs:
  lint:
    name: Review Dog - Lint GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Review Dog - actionlint
        uses: reviewdog/action-actionlint@v1
