name: ESLint
on:
  workflow_call:
    inputs:
      eslint-flags:
        description: Flags and arguments for eslint
        required: false
        type: string
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        type: boolean
      path:
        description: Path to search for files to lint
        required: true
        default: ${{github.workspace}}
        type: string
jobs:
  eslint:
    name: Review Dog - ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Review Dog - ESLint
        uses: reviewdog/action-eslint@b6303df522851d0e9abaea654da0222037d97e75 # v1.36.0
        with:
          eslint_flags: ${{inputs.eslint-flags}} ${{inputs.path}}
          fail_on_error: ${{inputs.fail-on-error}}
