name: Lint YAML
on:
  workflow_call:
    inputs:
      yamllint-flags:
        description: Flags and arguments for yamllint
        required: false
        type: string
      fail-on-error:
        description: Should reviewdog fail when errors are found
        required: false
        type: boolean
      workdir:
        description: Directory to search for files to lint
        required: true
        default: ${{github.workspace}}
        type: string
jobs:
  yamllint:
    name: Review Dog - Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Review Dog - yamllint
        uses: reviewdog/action-yamllint@8c429dfe4fc47b1ce1fa99a64e94693880d5dc30 # tag=v1
        with:
          yamllint_flags: ${{inputs.yamllint-flags}} ${{inputs.workdir}}
          fail_on_error: ${{inputs.fail-on-error}}
